stages:
  download:
    desc: Download and extract CIFAR-10 raw data
    cmd: python src/download.py
    deps:
      - src/download.py
    params:
      - download
    outs:
      - "${download.cifar_dir}"

  prepare:
    desc: Process raw data into train/val/test sets
    cmd: python src/ingestion.py
    deps:
      - src/ingestion.py
      - "${download.cifar_dir}"
    params:
      - download.cifar_dir
      - prepare
    outs:
      - "${prepare.train_split_path}"
      - "${prepare.val_split_path}"
      - "${prepare.test_split_path}"

  train:
    desc: Train the model
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - src/model.py
      - src/metrics.py
      - "${prepare.train_split_path}"
      - "${prepare.val_split_path}"
    params:
      - prepare.train_split_path
      - prepare.val_split_path
      - train
      - mlflow
    outs:
      - "${train.model_save_path}"
      - "${mlflow.run_id_path}"

  test:
    desc: Test the model
    cmd: python src/test_model.py
    deps:
      - src/test_model.py
      - src/model.py
      - src/metrics.py
      - "${mlflow.run_id_path}"
      - "${prepare.test_split_path}"
      - "${train.model_save_path}"
    params:
      - mlflow
